apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-rwo
  namespace: rox-demo
spec:
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"