apiVersion: v1
kind: Pod
metadata:
  name: populate
  namespace: rox-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    fsGroupChangePolicy: "OnRootMismatch"
  automountServiceAccountToken: false
  volumes:
    - name: demo-rwo
      persistentVolumeClaim:
        claimName: demo-rwo
  initContainers:
    - name: init-populate
      image: busybox:1.28
      command: ["/bin/sh"]
      args: ["-c", "/bin/base64 /dev/urandom | /bin/head -c 83886080 > /data/80mb.txt"]
      volumeMounts:
        - mountPath: /data
          name: demo-rwo
  containers:
    - name: populate
      imagePullPolicy: IfNotPresent
      image: busybox:1.28
      command: [ "/bin/tail", "-f", "/dev/null" ]
      volumeMounts:
        - mountPath: /data
          name: demo-rwo
